### ISSUE TITLE
Javascript Error with Mighty Text

### ISSUE THREAD

**Issue by aliusratio** [ramboxapp/community-edition#1286]
### Steps to reproduce

1. Switch to Mighty Text Tab

### Expected behavior

Switch to Mightytext Tab

### Actual behavior
Throws an exception window with: 

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 
    at updateBadge (/opt/Rambox/resources/app.asar/electron/main.js:288:7)
    at BrowserWindow.mainWindow.on (/opt/Rambox/resources/app.asar/electron/main.js:217:52)
    at emitTwo (events.js:106:13)
    at BrowserWindow.emit (events.js:194:7)
    at WebContents.webContents.on (/opt/Rambox/resources/electron.asar/browser/api/browser-window.js:81:10)
    at emitThree (events.js:116:13)
    at WebContents.emit (events.js:197:7)

### ENVIRONMENT

Linux Mint 18
Cinnamon WM

Version: 0.5.13
Platform: linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

**Comment by Ash258** [comment]
Continue in #1656
