### ISSUE TITLE
Dialog Erorr For Telegram

### ISSUE THREAD

**Issue by jayoharedee** [ramboxapp/community-edition#1296]
### Steps to reproduce

1. Add Telegram
2. Auth
3. Try to use

### Expected behavior

To be able to Telegrame

### Actual behavior

Pop-up dialog's with an exception appears when loading Telegram

### ENVIRONMENT

> Rambox: Newest Stable

> OS: High Sierra

> Arch: x64

Here is The stack trace from the dialog box
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 6478479397
    at updateBadge (/Applications/Rambox.app/Contents/Resources/app.asar/electron/main.js:288:7)
    at BrowserWindow.mainWindow.on (/Applications/Rambox.app/Contents/Resources/app.asar/electron/main.js:217:52)
    at emitTwo (events.js:106:13)
    at BrowserWindow.emit (events.js:194:7)
    at WebContents.webContents.on (/Applications/Rambox.app/Contents/Resources/electron.asar/browser/api/browser-window.js:81:10)
    at emitThree (events.js:116:13)
    at WebContents.emit (events.js:197:7)

**Comment by Ash258** [comment]
Continue in #1656
