### ISSUE TITLE
Glip account never loads (Uncaught Error: Could not call remote function 'bound ')

### ISSUE THREAD

**Issue by Rabusek** [ramboxapp/community-edition#1496]
### Steps to reproduce

1.  Open up Rambox
2.  Add glip
3.  Log into Glip account

### Expected behavior
Glip account loads up

### Actual behavior
Glip never loads up

### ENVIRONMENT
NOTE: THIS IS NOT reproducible on v0.5.14.

> Rambox: v0.5.15

> OS: Windows 10

> Arch: x64

![2018-02-28_21-01-36](https://user-images.githubusercontent.com/10826482/36810308-95cbb162-1cca-11e8-99cf-f9393811a562.gif)

LOG:
Uncaught Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: callback can only be called for once
Error: Could not call remote function 'bound '. Check that the function signature is correct. Underlying error: callback can only be called for once
    at callFunction (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\browser\rpc-server.js:324:5)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
    at WebContents.<anonymous> (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\browser\api\web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at callFunction (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\browser\rpc-server.js:324:5)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
    at WebContents.<anonymous> (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\browser\api\web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at Object.exception (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\renderer\api\remote.js:209:30)
    at metaToValue (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\renderer\api\remote.js:213:28)
    at remoteFunction (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\renderer\api\remote.js:230:16)
    at file:///C:/Users/patry/AppData/Local/Rambox/app-0.5.15/resources/app.asar/app.js:1:1627916
    at CallbacksRegistry.apply (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\common\api\callbacks-registry.js:46:25)
    at EventEmitter.ipcRenderer.on (C:\Users\patry\AppData\Local\Rambox\app-0.5.15\resources\electron.asar\renderer\api\remote.js:261:21)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)

**Comment by rndmerle** [comment]
Same issue with https://ticktick.com/#q/all/tasks
and https://cockpit-itsm.atlassian.net/secure/Dashboard.jspa

**Comment by Jiri-Kremser** [comment]
same issue when trying to add matrix as a custom service
