### ISSUE TITLE
JavaScript exception when trying to open an image on Skype

### ISSUE THREAD

**Issue by ramsito90** [ramboxapp/community-edition#1911]
If you click on an image someone sent you via Skype, you got an exception, and then a download dialog is opened.

> Uncaught Exception:
TypeError: mime.extension is not a function
    at Session.tmpWindow.webContents.session.once (/opt/Rambox/resources/app.asar/electron/main.js:349:42)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at Session.emit (events.js:217:7)

	
	-
	> Rambox 0.6.1
	> Electron 2.0.8
	> linux x64 4.4.0-137-generic

**Comment by Ash258** [comment]
#1907, #1891
