### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by tudor06** [ramboxapp/community-edition#1944]
Just tried to access one of the photos in a discussion. Get consitently:
Uncaught Exception:
TypeError: mime.extension is not a function
    at Session.tmpWindow.webContents.session.once (/Applications/Rambox.app/Contents/Resources/app.asar/electron/main.js:351:42)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at Session.emit (events.js:217:7)

	
	-
	> Rambox 0.6.2
	> Electron 2.0.8
	> darwin x64 18.0.0

**Comment by marknow22** [comment]
![error_002](https://user-images.githubusercontent.com/8896122/48154210-53ad4100-e2c8-11e8-828d-b36176d7890a.png)

Hi, same error here, rambox community version 0.6.2 on OSX Mojave, Ubuntu 18.04 and 16.04, Windows 8.1
