### ISSUE TITLE
Except Mastodon 502 Error

### ISSUE THREAD

**Issue by b3yond** [ramboxapp/community-edition#1947]
Our logs are spammed with this error:

```
Unknown Mastodon API Error.
Traceback (most recent call last):
  File "/srv/ticketfrei/active_bots/mastodonbot.py", line 27, in crawl
    notifications = m.notifications()
  File "<decorator-gen-15>", line 2, in notifications
  File "/srv/ticketfrei/lib/python3.5/site-packages/mastodon/Mastodon.py", line 57, in wrapper
    return function(self, *args, **kwargs)
  File "/srv/ticketfrei/lib/python3.5/site-packages/mastodon/Mastodon.py", line 577, in notifications
    return self.__api_request('GET', '/api/v1/notifications', params)
  File "/srv/ticketfrei/lib/python3.5/site-packages/mastodon/Mastodon.py", line 1613, in __api_request
    error_msg)
mastodon.Mastodon.MastodonAPIError: ('Mastodon API returned error', 502, 'Bad Gateway', None)
```

Let's stop logging this shit, we don't need the information that (unknown) mastodon admins are reloading apache or something similar

**Comment by b3yond** [comment]
oops, wrong project, sorry.
