### ISSUE TITLE
makeSingleInstance is not a function error on launch

### ISSUE THREAD

**Issue by gergely-xyz** [ramboxapp/community-edition#2356]
### Steps to reproduce
1. Install via pacaur
2. Launch from the terminal

### Behavior
Rambox failes to launch. Throws the following error:
```
App threw an error during load
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (/usr/lib/rambox/electron/main.js:370:24)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/usr/bin/rambox:29:19)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: app.makeSingleInstance is not a function
    at Object.<anonymous> (/usr/lib/rambox/electron/main.js:370:24)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/usr/bin/rambox:29:19)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
```

### ENVIRONMENT
> Rambox: v0.5.17-3
> OS: Manjaro Linux x86_64
> Arch: x64

**Comment by natedennis** [comment]
this should be reopened... just because users are moving on to other products because one wont launch doesnt mean this is not an issue. ive been seeing it for 2 weeks on arch linux

**Comment by natedennis** [comment]
https://electronjs.org/docs/all#planned-breaking-api-changes-40
